<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\WiimoteConnection.cs" Link="WiimoteConnection.cs" />
    <Reference Include="WiimoteLib.MotionPlus">
      <HintPath>..\libs\WiimoteLib.MotionPlus.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
